apiVersion: v1
kind: Service
metadata:
  labels:
    appdb: rsvpdb
  name: mongodb
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    appdb: rsvpdb
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    appdb: rsvpdb
  name: rsvpdb
spec:
  replicas: 1
  selector:
    matchLabels:
      appdb: rsvpdb
  template:
    metadata:
      labels:
        appdb: rsvpdb
    spec:
      containers:
      - image: mongo:3.3
        name: rsvpdb
        ports:
        - containerPort: 27017
